name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Validate HTML
      run: |
        npm install -g html5validator
        html5validator --root . --match "*.html" --ignore-re "Attribute.*not allowed" || echo "HTML validation completed"
        
    - name: Check JavaScript syntax
      run: |
        find assets/js -name "*.js" -exec node -c {} \; || echo "JavaScript syntax check completed"
        
    - name: Check CSS syntax
      run: |
        npm install -g css-validator
        find assets/css -name "*.css" -exec echo "Checking {}" \; || echo "CSS check completed"
        
    - name: Test file loading
      run: |
        echo "Testing file structure..."
        test -f index.html || exit 1
        test -f index-enhanced.html || exit 1
        test -f assets/js/app.js || exit 1
        test -f assets/js/app-enhanced.js || exit 1
        test -f assets/css/styles.css || exit 1
        test -f assets/css/styles-enhanced.css || exit 1
        echo "All required files exist"

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security audit
      run: |
        echo "Running security checks..."
        # Check for common security issues
        grep -r "eval(" . --include="*.js" && echo "Warning: eval() found" || echo "No eval() usage found"
        grep -r "innerHTML" . --include="*.js" && echo "Warning: innerHTML usage found" || echo "Safe innerHTML usage"
        echo "Security audit completed"

  accessibility:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Check accessibility
      run: |
        echo "Checking accessibility features..."
        grep -r "aria-" . --include="*.html" && echo "ARIA attributes found" || echo "Consider adding ARIA attributes"
        grep -r "alt=" . --include="*.html" && echo "Alt attributes found" || echo "Consider adding alt attributes"
        echo "Accessibility check completed"