name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install -g @lhci/cli
      - name: Start HTTP server
        run: |
          npm install -g http-server
          http-server . -p 8080 &
          sleep 5
      - name: Run Lighthouse CI
        run: |
          lhci autorun --collect.url=http://localhost:8080 --upload.target=temporary-public-storage